<!doctype>
<html>    
    <head>
        <title>Test layout</title>  
        <link href="/css/style.css" rel="stylesheet" />
    </head>
    
    <body>
        <div id="container">
            <header>
                <div id="logo">
                    <img src="/images/logo.jpg" alt="" />
                </div>
                              
                <nav>
                    <?php echo $this->navigation()->menu(); ?>   
                    <!---<ul>
                    <li><a href="/">Home</a></li>
                    <li><a href="/index/producten">Producten</a></li>
                    <li><a href="/contact">Contact</a></li>
                    </ul>
                    -->
                </nav>
            </header>
            
            <section id="content">
            <?php echo $this->layout()->content; ?>
            </section>    
        </div>
    </body>
</html>


